---
title: "KLU_APC2_Jinghang_Mountz_Data_Presentation"
author: "Li Jinghang, Ellie Mountz"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

``` {r dataCollect, include = FALSE, echo = FALSE}
rm(list=ls())
dev.off()
pacman::p_load(pacman, rio) 
library(tibble)
# IMPORTING Data ###########################################################
data <- import("~/Desktop/GitHub/KLU_APC2_Jinghang_Mountz_7_22_2020/KLU_APC2_Master_2020_07_22.xlsx")
activation <- import("~/Desktop/GitHub/KLU_APC2_Jinghang_Mountz_7_22_2020/Appending_to_Master/activ_values.txt")
AI <- import("~/Desktop/GitHub/KLU_APC2_Jinghang_Mountz_7_22_2020/Appending_to_Master/AI.txt")
FWHM <- import("~/Desktop/GitHub/KLU_APC2_Jinghang_Mountz_7_22_2020/Appending_to_Master/FWHM.txt")
FWHM <- abs(FWHM)
# Filter Data ##############################################################
data <- data[-c(which(data$FaceNames_Exclude == 'Yes')),]
data <- data[data$Visit_Relative == 1,] #Issues with face name data and only 1 scan/subject - 87 observations
list <- match(activation$Scan_ID,data$Vault_Scan_ID)
index <- which(list!=0,arr.ind = T)
list <- na.omit(match(activation$Scan_ID, data$Vault_Scan_ID))

#creating new variables that are going to be appended
data$Subject_ID <- NA
data$Scan_ID <- NA
data$Left_Hippocampus_Activation <- NA
data$Right_Hippocampus_Activation <- NA
data$Left_DLPFC_Activation <- NA
data$Right_DLPFC_Activation <- NA
data$Hippocampus_AI <- NA
data$DLPFC_AI <-NA
data$Left_Hippocampus_FWHM <- NA
data$Right_Hippocampus_FWHM <- NA
data$Left_DLPFC_FWHM <- NA
data$Right_DLPFC_FWHM <- NA

#appending
data$Subject_ID[list] <- activation$Subject_ID[index]
data$Scan_ID[list] <- activation$Scan_ID[index]
data$Left_Hippocampus_Activation[list] <- activation[,3][index]
data$Right_Hippocampus_Activation[list] <- activation[,4][index]
data$Left_DLPFC_Activation[list] <- activation[,5][index]
data$Right_DLPFC_Activation[list] <- activation[,6][index]
data$Hippocampus_AI[list] <- AI[,3][index]
data$DLPFC_AI[list] <- AI[,4][index]

data$Left_Hippocampus_FWHM[list] <- FWHM[,3][index]
data$Right_Hippocampus_FWHM[list] <- FWHM[,4][index]
data$Left_DLPFC_FWHM[list] <- FWHM[,5][index]
data$Right_DLPFC_FWHM[list] <- FWHM[,6][index]
# Recode Variables ##############################################################
data$Race_cat <- data$Race != 'White' #not white = 1 (True)
data$Education_cat <- data$Education > 12  #higher education = 1 (True)
data$Sex_cat <- (data$Sex == 'Male') #1 = male
data$Sex_cat[data$Sex == "NaN"] = NA
data$LETTER_FLUENCY <- (data$FLUENA + data$FLUENF+ data$FLUENS) / 3
data$WREC_TOT <- (data$WREC + data$WREC2 + data$WREC3)
data$STRINTERFERENCE <- (data$STRCW - data$STRCOL) / data$STRCOL
data$PiB_STATUS_CODE <- (data$PiBStatus_SUVR_GTM_FS_Global == "pos")
data$PiB_STATUS_CODE[data$PiBStatus_SUVR_GTM_FS_Global == "NaN"] = NA
data$APOE_CODE[data$APOE_CODE == "NaN"] = NA
data$Abs_Hippocampus_AI <- abs(data$Hippocampus_AI)
data$Abs_DLPFC_AI <- abs(data$DLPFC_AI)
data$FaceName_PostScanAccuracy[data$FaceName_PostScanAccuracy == "NA"] <- NA
data$FaceName_PostScanAccuracy <- as.numeric(data$FaceName_PostScanAccuracy)

#identifying PiB(+) subjects
x_l_h <- data$Left_Hippocampus_Activation[data$PiB_STATUS_CODE == TRUE]
y_l_h <- data$Left_Hippocampus_FWHM[data$PiB_STATUS_CODE == TRUE]
x_r_h <- data$Right_Hippocampus_Activation[data$PiB_STATUS_CODE == TRUE]
y_r_h <- data$Right_Hippocampus_FWHM[data$PiB_STATUS_CODE == TRUE]

x_l_d <-data$Left_DLPFC_Activation[data$PiB_STATUS_CODE == TRUE]
y_l_d <- data$Left_DLPFC_FWHM[data$PiB_STATUS_CODE == TRUE]
x_r_d <-data$Right_DLPFC_Activation[data$PiB_STATUS_CODE == TRUE]
y_r_d <- data$Right_DLPFC_FWHM[data$PiB_STATUS_CODE == TRUE]
#visulize data#################################################################
plot(data$Left_Hippocampus_Activation, data$Left_Hippocampus_FWHM,col="red", pch = 1, xlab="Mean Activation", ylab="FWHM")
points(data$Right_Hippocampus_Activation, data$Right_Hippocampus_FWHM, pch = 2, col="black")
points(x_l_h,y_l_h,pch = 4, cex = 2)
points(x_r_h,y_r_h,pch = 4, cex = 2)
legend(x=-2.5,y=27,c("Left Hippocampus", "Right Hippocampus", "PiB(+) Subjects"),cex=.8,col=c("red","black","black"),pch=c(1,2,4))

plot(data$Left_DLPFC_Activation, data$Left_DLPFC_FWHM,col="blue", pch = 1, xlab="Mean Activation", ylab="FWHM")
points(data$Right_DLPFC_Activation, data$Right_DLPFC_FWHM, col = "brown", pch =2)
points(x_l_d,y_l_d,pch = 4, cex = 2)
points(x_r_d,y_r_d,pch = 4, cex = 2)
legend(x=-4,y=35,c("Left DLPFC", "Right DLPFC","PiB(+) Subjects"),cex=.8,col=c("blue","brown","black"),pch=c(1,2,4))

# Cognitive Domain - Z Transform ####################################################################
#Negative z value means that lower value = higher performance
# doi:10.1016/j.jalz.2017.12.003 - method of composite calculation
#doi/ 10.1136/jnnp.2004.045567 - standard deviations from normative data
CLOCKD_Z <- (data$CLOCKD - mean(data$CLOCKD, na.rm = TRUE)) / sd(data$CLOCKD, na.rm = TRUE)
BLOCKDES_Z <- (data$BLOCKDES - mean(data$BLOCKDES, na.rm = TRUE)) / sd(data$BLOCKDES, na.rm = TRUE)
BNT60TOT_Z <- (data$BNT60TOT - mean(data$BNT60TOT, na.rm = TRUE)) / sd(data$BLOCKDE, na.rm = TRUE)
REYCO_Z <- (data$REYCO - mean(data$REYCO, na.rm = TRUE)) / sd (data$REYCO, na.rm = TRUE)
REYIM_Z <- (data$REYIM-mean(data$REYIM, na.rm = TRUE)) / sd(data$REYIM, na.rm = TRUE)
REYDE_Z <- (data$REYDE - mean(data$REYDE, na.rm = TRUE)) / sd(data$REYDE, na.rm = TRUE)
FLUEN_Z <- (data$FLUEN - mean(data$FLUEN, na.rm = TRUE)) / sd(data$FLUEN, na.rm = TRUE)
LETTER_FLUENCY_Z <- (data$LETTER_FLUENCY - mean(data$LETTER_FLUENCY, na.rm = TRUE)) / sd(data$LETTER_FLUENCY, na.rm=TRUE)
WREC_TOT_Z <- (data$WREC_TOT - mean(data$WREC_TOT, na.rm = TRUE)) / sd(data$WREC_TOT, na.rm =TRUE)
WRECDE_Z <- (data$WRECDE - mean(data$WRECDE, na.rm = TRUE)) / sd(data$WRECDE, na.rm = TRUE)
SPANSF_Z <- (data$SPANSF - mean(data$SPANSF, na.rm = TRUE)) / sd(data$SPANSF, na.rm = TRUE)
SPANSB_Z <- (data$SPANSB - mean(data$SPANSB, na.rm = TRUE)) / sd(data$SPANSB, na.rm = TRUE)
TRAILAS_Z <- (data$TRAILAS - mean(data$TRAILAS, na.rm = TRUE)) / sd(data$TRAILAS, na.rm = TRUE)
TRAILBS_Z <- (data$TRAILBS - mean(data$TRAILBS, na.rm = TRUE)) / sd(data$TRAILBS, na.rm= TRUE)
LMIAIMM_Z <- (data$LMIAIMM - mean(data$LMIAIMM, na.rm = TRUE)) /sd(data$LMIAIMM, na.rm = TRUE)
LMIIADEL_Z <- (data$LMIIADEL - mean(data$LMIIADEL, na.rm = TRUE))/sd(data$LMIIADEL, na.rm = TRUE)
DIGSYMWR_Z <- (data$DIGSYMWR - mean(data$DIGSYMWR, na.rm = TRUE))/sd(data$DIGSYMWR, na.rm = TRUE)
STRCW_Z <- (data$STRCW - mean(data$STRCW, na.rm = TRUE)) / sd(data$STRCW, na.rm = TRUE)
TRAILAS_Z_INV <- -1 * TRAILAS_Z
TRAILBS_Z_INV <- -1 * TRAILBS_Z

# Domain Scores #########################################################################
#doi:10.1016/j.jalz.2017.12.003., doi:10.1080/13607860903071014. (Both Beth Snitz articles), https://www.ncbi.nlm.nih.gov/books/NBK285344/ - for SPANSB in Executive
data$memory_learning <- (LMIAIMM_Z + REYIM_Z + WREC_TOT_Z) / 3
data$memory_retrieval <- (LMIIADEL_Z + REYDE_Z + WRECDE_Z) / 3 
data$visiospatial <- (BLOCKDES_Z + REYCO_Z) / 2
data$language <- (FLUEN_Z + LETTER_FLUENCY_Z + BNT60TOT_Z) / 3
data$executive_attention <- (TRAILAS_Z_INV + TRAILBS_Z_INV + CLOCKD_Z + DIGSYMWR_Z + STRCW_Z + SPANSF_Z + SPANSB_Z) / 7
```

``` {r intraclass_correlation, include = FALSE, echo = FALSE}
#Intraclass Correlation ################################################################
# Pearson (Linear Correlation between composite and raw scores)
library("irr")
#Memory_Learning
REYIM_Pearson_Correlation <- cor(data$memory_learning, data$REYIM, use = "complete.obs")
LMIAIMM_Pearson_Correlation <- cor(data$memory_learning, data$LMIAIMM, use = "complete.obs")
WREC_TOT_Pearson_Correlation <- cor(data$memory_learning, data$WREC_TOT, use = "complete.obs")

#Memory_Retrieval
LMIIADEL_Pearson_Correlation <- cor(data$memory_learning, data$LMIIADEL, use = "complete.obs")
REYDE_Pearson_Correlation <- cor(data$memory_learning, data$REYDE, use = "complete.obs")
WRECDE_Pearson_Correlation <- cor(data$memory_learning, data$WRECDE, use = "complete.obs")

# Visiospatial
BLOCKDES_Pearson_Correlation <- cor(data$visiospatial, data$BLOCKDES, use = "complete.obs")
REYCO_Pearson_Correlation <- cor(data$visiospatial, data$REYCO, use = "complete.obs")

#Langugae
BNT60TOT_Pearson_Correlation <- cor(data$language, data$BNT60TOT, use = "complete.obs")
FLUEN_Pearson_Correlation <- cor(data$language, data$FLUEN, use = "complete.obs")
LETTER_FLUENCY_Pearson_Correlation <- cor(data$language, data$LETTER_FLUENCY, use = "complete.obs")

#Executive_Attention
TRAILBS_Combo_Pearson_Correlation <- cor(data$executive_attention, -1*data$TRAILBS, use = "complete.obs")
TRAILAS_Combo_Pearson_Correlation <- cor(data$executive_attention, -1*data$TRAILAS, use = "complete.obs")
SPANSF_Combo_Pearson_Correlation <- cor(data$executive_attention, data$SPANSF, use = "complete.obs")
DIGSYMWR_Combo_Pearson_Correlation <- cor(data$executive_attention, data$DIGSYMWR, use = "complete.obs")
SPANSB_Combo_Pearson_Correlation <- cor(data$executive_attention, data$SPANSB, use = "complete.obs")
CLOCKD_combo_Pearson_Correlation <- cor(data$executive_attention, data$CLOCKD, use = "complete.obs")

```

``` {r pval_calc, echo = FALSE, include = FALSE}
#For p-values
lmp <- function (modelobject) {
  if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
  f <- summary(modelobject)$fstatistic
  p <- pf(f[1],f[2],f[3],lower.tail=F)
  attributes(p) <- NULL
  return(p)
}
```

``` {r Abs_hippocampus, echo = FALSE}
mdl_Abs_hippocampus_AI <- lm(Abs_Hippocampus_AI ~ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

abs_hippocampus_rsquared <- summary(mdl_Abs_hippocampus_AI)$r.squared
abs_hippocampus_fstat <- summary(mdl_Abs_hippocampus_AI)$fstatistic[1]
abs_hippocampus_df1 <- summary(mdl_Abs_hippocampus_AI)$fstatistic[2]
abs_hippocampus_df2 <- summary(mdl_Abs_hippocampus_AI)$fstatistic[3]
abs_hippocampus_pval <- lmp(mdl_Abs_hippocampus_AI)
```

``` {r Abs_DLPFC, echo = FALSE}
mdl_Abs_DLPFC_AI <- lm(Abs_DLPFC_AI ~ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

abs_DLPFC_rsquared <- summary(mdl_Abs_DLPFC_AI)$r.squared
abs_DLPFC_fstat <- summary(mdl_Abs_DLPFC_AI)$fstatistic[1]
abs_DLPFC_df1 <- summary(mdl_Abs_DLPFC_AI)$fstatistic[2]
abs_DLPFC_df2 <- summary(mdl_Abs_DLPFC_AI)$fstatistic[3]
abs_DLPFC_pval <- lmp(mdl_Abs_DLPFC_AI)

```

``` {r memory_learning_abs, echo = FALSE}
# Cognitive Factors  - Absolute AI################################################################
mdl_memory_learning_abs_AI <- lm(memory_learning ~ FaceName_PostScanAccuracy+Abs_DLPFC_AI + Abs_Hippocampus_AI+ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

memory_learning_abs_rsquared <- summary(mdl_memory_learning_abs_AI)$r.squared
memory_learning_abs_fstat <- summary(mdl_memory_learning_abs_AI)$fstatistic[1]
memory_learning_abs_df1 <- summary(mdl_memory_learning_abs_AI)$fstatistic[2]
memory_learning_abs_df2 <- summary(mdl_memory_learning_abs_AI)$fstatistic[3]
memory_learning_abs_pval <- lmp(mdl_memory_learning_abs_AI)

```

``` {r memory_retrieval_abs, echo = FALSE}
mdl_memory_retrieval_abs_AI <- lm(memory_retrieval ~ FaceName_PostScanAccuracy+Abs_DLPFC_AI + Abs_Hippocampus_AI+ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

memory_retrieval_abs_rsquared <- summary(mdl_memory_retrieval_abs_AI)$r.squared
memory_retrieval_abs_fstat <- summary(mdl_memory_retrieval_abs_AI)$fstatistic[1]
memory_retrieval_abs_df1 <- summary(mdl_memory_retrieval_abs_AI)$fstatistic[2]
memory_retrieval_abs_df2 <- summary(mdl_memory_retrieval_abs_AI)$fstatistic[3]
memory_retrieval_abs_pval <- lmp(mdl_memory_retrieval_abs_AI)

```

``` {r visiospatial_abs, echo = FALSE}

mdl_visiospatial_abs_AI <- lm(visiospatial ~ FaceName_PostScanAccuracy+Abs_DLPFC_AI + Abs_Hippocampus_AI+ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

visiospatial_abs_rsquared <- summary(mdl_visiospatial_abs_AI)$r.squared
visiospatial_abs_fstat <- summary(mdl_visiospatial_abs_AI)$fstatistic[1]
visiospatial_abs_df1 <- summary(mdl_visiospatial_abs_AI)$fstatistic[2]
visiospatial_abs_df2 <- summary(mdl_visiospatial_abs_AI)$fstatistic[3]
visiospatial_abs_pval <- lmp(mdl_visiospatial_abs_AI)

```

``` {r language_abs, echo = FALSE}

mdl_language_abs_AI <- lm(language ~ FaceName_PostScanAccuracy+Abs_DLPFC_AI + Abs_Hippocampus_AI+ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

language_abs_rsquared <- summary(mdl_language_abs_AI)$r.squared
language_abs_fstat <- summary(mdl_language_abs_AI)$fstatistic[1]
language_abs_df1 <- summary(mdl_language_abs_AI)$fstatistic[2]
language_abs_df2 <- summary(mdl_language_abs_AI)$fstatistic[3]
language_abs_pval <- lmp(mdl_language_abs_AI)

```

``` {r executive_attention_abs, echo = FALSE}
mdl_executive_attention_abs_AI <- lm(executive_attention ~ FaceName_PostScanAccuracy+Abs_DLPFC_AI + Abs_Hippocampus_AI+ Age_CurrentVisit+Sex_cat+Race_cat+Education_cat+FDG_SUVR_GTM_FS_Global+PiB_STATUS_CODE+APOE_CODE, data = data)

executive_attention_abs_rsquared <- summary(mdl_executive_attention_abs_AI)$r.squared
executive_attention_abs_fstat <- summary(mdl_executive_attention_abs_AI)$fstatistic[1]
executive_attention_abs_df1 <- summary(mdl_executive_attention_abs_AI)$fstatistic[2]
executive_attention_abs_df2 <- summary(mdl_executive_attention_abs_AI)$fstatistic[3]
executive_attention_abs_pval <- lmp(mdl_executive_attention_abs_AI)
```

<!-- ``` { r new_model, echo = FALSE} -->

<!-- ``` -->

``` {r modelSetUp, echo = FALSE, include = FALSE}
if (!require("sjPlot")) install.packages("sjPlot")
library(sjPlot)
if (!require("kableExtra")) install.packages("kableExtra")
library(knitr)
library(kableExtra)
if (!require("scales")) install.packages("scales")
library(scales)
```

## Cohort Demographics:

``` {r demographicsData, echo = FALSE}
# Demographics Table ###############################################################

#Calculate Data - Some data missing
num_subjects <- nrow(data)

n_education <- length(data$Education_cat[!is.na(data$Education_cat)])
mean_education <- mean(data$Education, na.rm = TRUE)
stdv_education <- sd(data$Education, na.rm = TRUE)
education_over_12 <- sum(data$Education_cat, na.rm = TRUE)
education_under_12 <- length(data$Education_cat)-sum(data$Education_cat, na.rm = TRUE) - sum(is.na(data$Education_cat))
percent_over_12 <- education_over_12 / (length(data$Education_cat) - sum(is.na(data$Education_cat)))
percent_under_12 <- education_under_12 / (length(data$Education_cat) - sum(is.na(data$Education_cat)))

n_age <- length(data$Age_CurrentVisit[!is.na(data$Age_CurrentVisit)])
mean_age <- mean(data$Age_CurrentVisit, na.rm = TRUE)
age_stdv <- sd(data$Age_CurrentVisit, na.rm = TRUE)

n_sex <- length(data$Sex_cat[!is.na(data$Sex_cat)])
male_count <- sum(data$Sex == "Male", na.rm = TRUE)
percent_male <- male_count / (length(data$Sex) - sum(data$Sex == ""))
female_count <- sum(data$Sex == "Female", na.rm = TRUE)
percent_female <- female_count / (length(data$Sex) - sum(data$Sex == ""))

n_race <- length(data$Race_cat[!is.na(data$Race_cat)])
white_count <- sum(data$Race == "White")
percent_white <- white_count / (length(data$Race) - sum(data$Race == ""))
black_count <- sum(data$Race == "Black")
percent_black <- black_count / (length(data$Race) - sum(data$Race == ""))
asian_count <- sum(data$Race == "Asian")
percent_asian <- asian_count / (length(data$Race) - sum(data$Race == ""))

```

<div style="margin-bottom:100px;">
``` {r, echo = FALSE}
#Make Table
demographic_data <- data.frame(Variable = c("Total_Subjects","n", "Mean", "Standard Deviation", "Over 12 Years", "Under 12 Years", "n","Mean", "Standard Deviation", "n","Male Count", "Female Count", "n","White Count", "Black Count", "Asian Count"),
                               Value = c(num_subjects, n_education, mean_education, stdv_education, education_over_12, education_under_12,n_age, mean_age, age_stdv, n_sex, male_count, female_count, n_race, white_count,black_count,asian_count),
                               Percent = c("", "", "","", label_percent()(percent_over_12), label_percent()(percent_under_12),"","","","",label_percent()(percent_male), label_percent()(percent_female),"",label_percent()(percent_white),label_percent()(percent_black),label_percent()(percent_asian)))

kable(demographic_data, caption = "Demographic data for normal aging", digits = 2) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left") %>%
                pack_rows("Education", 2,6) %>%
                pack_rows("Age", 7,9) %>%
                pack_rows("Sex", 10,12) %>%
                pack_rows("Race", 13,16)

```
</div>

## Regression Models:

## Hemispheric Asymmetry Models

**Hippocampus Absolute Asymmetry Index Data**
<div style="margin-bottom:100px;">
``` {r abs_hippocampus_data, echo = FALSE}
abs_hippocampus_data <- data.frame(Variable = c(paste("F( ", abs_hippocampus_df1, ",", abs_hippocampus_df2,")"),"R^2","p-value"),
                               Value = c(abs_hippocampus_fstat,abs_hippocampus_rsquared,abs_hippocampus_pval))

kable(abs_hippocampus_data, caption = "Hippocampus Absolute AI Model Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

```

``` {r abs_hippocampus_coefficients, echo = FALSE}
tab_model(mdl_Abs_hippocampus_AI, dv.labels = "Hippocampus Absolute AI",
          pred.labels = c("Intercept","Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

**DLPFC Absolute Asymmetry Index Data** 
<div style="margin-bottom:100px;">
``` {r abs_DLPFC_data, echo = FALSE}
abs_DLPFC_data <- data.frame(Variable = c(paste("F( ", abs_DLPFC_df1, ",", abs_DLPFC_df2,")"),"R^2","p-value"),
                               Value = c(abs_DLPFC_fstat,abs_DLPFC_rsquared,abs_DLPFC_pval))

kable(abs_DLPFC_data, caption = "DLPFC Absolute AI Model Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r abs_DLPFC_coefficients, echo = FALSE}
tab_model(mdl_Abs_DLPFC_AI, dv.labels = "DLPFC Absolute AI",
          pred.labels = c("Intercept","Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

## Cogntive Domains

**Interclass Correlation**

<!-- ``` {r domain_correlation, echo = FALSE} -->
<!-- # Correlation Tables ######################################################################## -->
<!-- Pearson_Correlation_data <- data.frame(Variable = c("Modified Rey Figure Delayed Recall","Modified Rey Figure Immediate Recall", "Modified Block Design","Modified Rey Figure Copy","Boston Naming Test (30-item)","Fluency - Animals","Trails B","Digit Span Backward","Trails A","Digit Span Forward","Digit Symbol Substitution Test","Trails A","Digit Span Forward","Trails B","Digit Span Backward"), -->
<!--                                        Pearson_Correlation = c(REYDE_Pearson_Correlation,REYIM_Pearson_Correlation,BLOCKDES_Pearson_Correlation,REYCO_Pearson_Correlation, BOSTON1_Pearson_Correlation, FLUEN_Pearson_Correlation, TRAILBS_Pearson_Correlation,SPANSB_Pearson_Correlation, TRAILAS_Pearson_Correlation,SPANSF_Pearson_Correlation, DIGSYMWR_Combo_Pearson_Correlation, TRAILAS_Combo_Pearson_Correlation,SPANSF_Combo_Pearson_Correlation,TRAILBS_Combo_Pearson_Correlation,SPANSB_Combo_Pearson_Correlation)) -->
<!-- ``` -->

<!-- <div style="margin-bottom:100px;"> -->
<!-- ``` {r domain_correlation_make_table, echo=FALSE} -->
<!-- kable(Pearson_Correlation_data, caption = "Pearson Interclass Correlation Values for Cognitive Domains. Measures linear correlation between raw cognitive test scores and the corresponding composite cognitive domain score.", digits = 2) %>% -->
<!--   kable_styling(bootstrap_options = "striped", full_width = F, position = "left") %>% -->
<!--   pack_rows("Memory Domain",1,2) %>% -->
<!--   pack_rows("Visiospatial Domain",3,4) %>% -->
<!--   pack_rows("Language Domain",5,6) %>% -->
<!--   pack_rows("Executive Domain",7,8) %>% -->
<!--   pack_rows("Attention Domain",9,10) %>% -->
<!--   pack_rows("Executive_Attention Domain",11,15) -->
<!-- ``` -->
<!-- </div> -->

**Memory Learning Domain**
<div style="margin-bottom:100px;">
``` {r memory_learning_abs_data, echo = FALSE}
memory_learning_abs_data <- data.frame(Variable = c(paste("F( ", memory_learning_abs_df1, ",", memory_learning_abs_df2,")"),"R^2","p-value"),
                               Value = c(memory_learning_abs_fstat,memory_learning_abs_rsquared,memory_learning_abs_pval))

kable(memory_learning_abs_data, caption = "Memory Learning Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r memory_learning_abs_coefficients, echo = FALSE}
tab_model(mdl_memory_learning_abs_AI, dv.labels = "Memory Learning",
          pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

**Memory Retrieval Learning Domain**
<div style="margin-bottom:100px;">
``` {r memory_abs_data, echo = FALSE}
memory_retrieval_abs_data <- data.frame(Variable = c(paste("F( ", memory_retrieval_abs_df1, ",", memory_retrieval_abs_df2,")"),"R^2","p-value"),
                               Value = c(memory_retrieval_abs_fstat,memory_retrieval_abs_rsquared,memory_retrieval_abs_pval))

kable(memory_retrieval_abs_data, caption = "Memory Retrieval Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r memory_abs_coefficients, echo = FALSE}
tab_model(mdl_memory_retrieval_abs_AI, dv.labels = "Memory Retrieval",
          pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

**Visiospatial Domain**
<div style="margin-bottom:100px;">
``` {r visiospatial_abs_data, echo = FALSE}
visiospatial_abs_data <- data.frame(Variable = c(paste("F( ", visiospatial_abs_df1, ",", visiospatial_abs_df2,")"),"R^2","p-value"),
                               Value = c(visiospatial_abs_fstat,visiospatial_abs_rsquared,visiospatial_abs_pval))

kable(visiospatial_abs_data, caption = "Visiospatial Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r visiospatial_abs_coefficients, echo = FALSE}
tab_model(mdl_visiospatial_abs_AI, dv.labels = "Visiospatial",
          pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

**Language Domain**
<div style="margin-bottom:100px;">
``` {r language_abs_data, echo = FALSE}
language_abs_data <- data.frame(Variable = c(paste("F( ", language_abs_df1, ",", language_abs_df2,")"),"R^2","p-value"),
                               Value = c(language_abs_fstat,language_abs_rsquared, language_abs_pval))

kable(language_abs_data, caption = "Language Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r language_abs_coefficients, echo = FALSE}
tab_model(mdl_language_abs_AI, dv.labels = "Language",
          pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>

**Executive_Attention Domain**
<div style="margin-bottom:100px;">
``` {r executive_attention_abs_data, echo = FALSE}
executive_attention_abs_data <- data.frame(Variable = c(paste("F( ", executive_attention_abs_df1, ",", executive_attention_abs_df2,")"),"R^2","p-value"),
                               Value = c(executive_attention_abs_fstat,executive_attention_abs_rsquared, executive_attention_abs_pval))

kable(executive_attention_abs_data, caption = "Executive_Attention Summary", digits = 3) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

``` {r executive_attention_abs_coefficients, echo = FALSE}
tab_model(mdl_executive_attention_abs_AI, dv.labels = "Executive_Attention",
          pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race",
                          "Education (years)", "FDG Global", 
                          "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE)
```
</div>


# FWHM Regressions

**New Model**

<!-- <div style="margin-bottom:100px;"> -->
<!-- ``` {r new_model_data, echo = FALSE} -->
<!-- new_model_data <- data.frame(Variable = c(paste("F( ", new_model_df1, ",", new_model_df2,")"),"R^2","p-value"), -->
<!--                                Value = c(new_model_fstat,new_model_rsquared, new_model_pval)) -->

<!-- kable(new_model_data, caption = "New Model Name Summary", digits = 3) %>% -->
<!--   kable_styling(bootstrap_options = "striped", full_width = F, position = "left") -->
<!-- ``` -->

<!-- ``` {r executive_attention_abs_coefficients, echo = FALSE} -->
<!-- tab_model(new_model, dv.labels = "New Model Title", -->
<!--           pred.labels = c("Intercept","Task Accuracy","DLPFC Absolute AI", "Hippocampus Absolute AI", "Age at Visit", "Sex", "Race", -->
<!--                           "Education (years)", "FDG Global",  -->
<!--                           "PiB Global Status", "APOE Status"), show.r2 = FALSE, show.ci = FALSE) -->
<!-- ``` -->
<!-- </div> -->





